### ISSUE TITLE
Issues raised by PCMDI review of CMIP6 variables - Master list

### ISSUE THREAD

**Issue by martinjuckes** [CMIP-Data-Request/Harmonised-Public-Consultation#30]
The [Branding of CMIP6 Variables workbook](https://docs.google.com/spreadsheets/d/1_y7OnhSvWc_Cjwnf8dSZcvuVC9BQuSQTPYRWYM1Q9Oc) contains a review of CMIP6 variables and suggests a number of metadata modifications. 

This issue links to other issues raised for specific suggestions:

- [x] Eday and LImon agesno (Age of Snow) https://github.com/CMIP-Data-Request/Harmonised-Consultation-Phase-1/issues/27 [DONE]
- [ ] Air Pressure at Convective Cloud Base https://github.com/CMIP-Data-Request/Harmonised-Consultation-Phase-1/issues/28 [ACCEPTED - QUERY OPEN]
- [x] Pressure level area means: https://github.com/CMIP-Data-Request/Harmonised-Consultation-Phase-1/issues/29 [DONE]
- [ ] co2mass cell methods: https://github.com/CMIP-Data-Request/Harmonised-Consultation-Phase-1/issues/31
- [x] longitude: time: mean where air: https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/44 [DONE]
- [ ] where land over all area types https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/45  .. should be accepted for area fraction variables which are defined as zero over sea, not for variables which are undefined away from land grid [TODO]
- [ ] simpconc https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/46 [REJECTED]
- [x] sum through atmospheric column height: sum (through atmospheric column) area: sum time: mean [DONE]
- [ ] Convective cloud optical depth https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/48 [OPEN]
- [x] Grounded ice sheet for bedrock: https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/49 [DONE]
- [ ] Canopy albedo: https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/50 [OPEN]
- [x] Efx.vegHeight https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/51 [DONE]
- [x] prsnc https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/52 [REJECTED]
- [x] unfrozen soil clarification https://github.com/CMIP-Data-Request/Harmonised-Public-Consultation/issues/53 [DONE]
- [x] cell methods changed to include "where sea" in ocean model level climatologies. [DONE]
- [ ] Remove comment from cell methods : no justification for proposed change [e.g. SImon.sfdsi] [#57]
- [ ] Expand `cell_methods = time: mean` for tauuo and related ocean fields [DONE]
- [ ] Change cell methods for 6hrLev.ua, 6hrLev.va [#58]
- [ ] Cloud sampling [#59] in progress.
- [x ] Ice sheet area: change `area: mean` to `area:sum` [DONE]

Covered up to, but not including, row 489

**Comment by durack1** [comment]
Great, glad we're making progress on this.

@martinjuckes could you point to where your changes have been made, that will allow these to be pulled back across to the mip-cmor-tables so we can ensure synchronization as soon as possible

**Comment by durack1** [comment]
@martinjuckes @charliepascoe @jamesanstey @mpmoine @taylor13 I was keen to ascertain how best (and without duplication) to continue to raise issues in the DR v1.1 that need addressing. Is this repo preferred, or would you prefer that we duplicate the issues using the airtables form ([here](https://airtable.com/appas2EDANenGxXdp/pagUouM2FWh9ZrRQV/form))?

**Comment by JamesAnstey** [comment]
@durack1 I think the [airtable variables comment form ](https://airtable.com/appas2EDANenGxXdp/pagUouM2FWh9ZrRQV/form) is the best way to bring *new* issues with variables to the attention of the thematic author teams. On Thurs (Jan 30) with the v1.1 release there will be a webpage outlining the available feedback mechanisms (including spreadsheets for modelling centres and MIPs) similar to the previous releases (v1.0 & v1.0beta). But for issues already being tracked in this repo, such as the ones in the [spreadsheet](https://docs.google.com/spreadsheets/d/1_y7OnhSvWc_Cjwnf8dSZcvuVC9BQuSQTPYRWYM1Q9Oc) that @martinjuckes referred to at the start of this issue, I don't see a need to duplicate them by using the airtable comment form. Others please jump in here if I'm missing something.

**Comment by martinjuckes** [comment]
This discussion has been superseded by new issues raised after v1.1 release.
